export const ADVENTURER_LOADING = 'ADVENTURER_LOADING';
export const FETCH_LIST_ADVENTURERS = 'FETCH_LIST_ADVENTURERS';
export const ADVENTURERS_LIST = 'ADVENTURERS_LIST';
export const CREATE_NEW_ADVENTURER = 'CREATE_NEW_ADVENTURER';
export const EXIT_ADVENTURER_CREATION = 'EXIT_ADVENTURER_CREATION';
export const FETCH_CREATE_ADVENTURER = 'FETCH_CREATE_ADVENTURER';
