export const ADVENTURER_LOADING = 'ADVENTURER_LOADING';
export const CREATE_NEW_ADVENTURER = 'CREATE_NEW_ADVENTURER';
export const EXIT_ADVENTURER_CREATION = 'EXIT_ADVENTURER_CREATION';
export const FETCH_CREATE_ADVENTURER = 'FETCH_CREATE_ADVENTURER';
